language: python
python:
  - "3.6"
script:
  - pytest

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
after_success:
  - coveralls