language: python
python:
  - "3.6"
  install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - pytest --with-coverage
after_success:
  - coveralls