language: python
python:
  - "3.6"
script:
  - pytest
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
  # - pip install pytest
  # - pip install pytest-cov
after_success:
  - coveralls